// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_AddTransaction_FullMethodName         = "/ledger.v1.LedgerService/AddTransaction"
	LedgerService_ListTransactions_FullMethodName       = "/ledger.v1.LedgerService/ListTransactions"
	LedgerService_SetBudget_FullMethodName              = "/ledger.v1.LedgerService/SetBudget"
	LedgerService_ListBudgets_FullMethodName            = "/ledger.v1.LedgerService/ListBudgets"
	LedgerService_GetReportSummary_FullMethodName       = "/ledger.v1.LedgerService/GetReportSummary"
	LedgerService_BulkImportTransactions_FullMethodName = "/ledger.v1.LedgerService/BulkImportTransactions"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	AddTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	ListTransactions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	SetBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*Budget, error)
	ListBudgets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBudgetsResponse, error)
	GetReportSummary(ctx context.Context, in *ReportSummaryRequest, opts ...grpc.CallOption) (*ReportSummaryResponse, error)
	BulkImportTransactions(ctx context.Context, in *BulkImportTransactionsRequest, opts ...grpc.CallOption) (*BulkImportTransactionsResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) AddTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, LedgerService_AddTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListTransactions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) SetBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*Budget, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Budget)
	err := c.cc.Invoke(ctx, LedgerService_SetBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListBudgets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBudgetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBudgetsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListBudgets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetReportSummary(ctx context.Context, in *ReportSummaryRequest, opts ...grpc.CallOption) (*ReportSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSummaryResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetReportSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) BulkImportTransactions(ctx context.Context, in *BulkImportTransactionsRequest, opts ...grpc.CallOption) (*BulkImportTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkImportTransactionsResponse)
	err := c.cc.Invoke(ctx, LedgerService_BulkImportTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	AddTransaction(context.Context, *CreateTransactionRequest) (*Transaction, error)
	ListTransactions(context.Context, *emptypb.Empty) (*ListTransactionsResponse, error)
	SetBudget(context.Context, *CreateBudgetRequest) (*Budget, error)
	ListBudgets(context.Context, *emptypb.Empty) (*ListBudgetsResponse, error)
	GetReportSummary(context.Context, *ReportSummaryRequest) (*ReportSummaryResponse, error)
	BulkImportTransactions(context.Context, *BulkImportTransactionsRequest) (*BulkImportTransactionsResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) AddTransaction(context.Context, *CreateTransactionRequest) (*Transaction, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTransaction not implemented")
}
func (UnimplementedLedgerServiceServer) ListTransactions(context.Context, *emptypb.Empty) (*ListTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedLedgerServiceServer) SetBudget(context.Context, *CreateBudgetRequest) (*Budget, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBudget not implemented")
}
func (UnimplementedLedgerServiceServer) ListBudgets(context.Context, *emptypb.Empty) (*ListBudgetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBudgets not implemented")
}
func (UnimplementedLedgerServiceServer) GetReportSummary(context.Context, *ReportSummaryRequest) (*ReportSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReportSummary not implemented")
}
func (UnimplementedLedgerServiceServer) BulkImportTransactions(context.Context, *BulkImportTransactionsRequest) (*BulkImportTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkImportTransactions not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_AddTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).AddTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_AddTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).AddTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListTransactions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_SetBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).SetBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_SetBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).SetBudget(ctx, req.(*CreateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListBudgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListBudgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListBudgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListBudgets(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetReportSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetReportSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetReportSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetReportSummary(ctx, req.(*ReportSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_BulkImportTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkImportTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).BulkImportTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_BulkImportTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).BulkImportTransactions(ctx, req.(*BulkImportTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTransaction",
			Handler:    _LedgerService_AddTransaction_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _LedgerService_ListTransactions_Handler,
		},
		{
			MethodName: "SetBudget",
			Handler:    _LedgerService_SetBudget_Handler,
		},
		{
			MethodName: "ListBudgets",
			Handler:    _LedgerService_ListBudgets_Handler,
		},
		{
			MethodName: "GetReportSummary",
			Handler:    _LedgerService_GetReportSummary_Handler,
		},
		{
			MethodName: "BulkImportTransactions",
			Handler:    _LedgerService_BulkImportTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger/v1/ledger.proto",
}
